# =====================================================
# DEV ENVIRONMENT SETUP FOR OPENGROWBOX
# =====================================================
#
# Diese Vorlage zeigt, wie Devices und Entities konfiguriert
# werden müssen, damit sie vom DeviceManager und RegistryListener
# korrekt erkannt werden.
#
# KONVENTIONEN:
# 1. area_id MUSS mit OGB-Raum-Namen übereinstimmen
# 2. device_id MUSS eindeutig sein (unique_id)
# 3. Entities MUSS über device_id einem Device zugeordnet werden
# 4. Labels definieren den Device-Typ (siehe device_types.yaml)
# 5. Entity-Namen müssen relevante Keywords enthalten
#
# =====================================================

# =====================================================
# AREA DEFINITION
# =====================================================
# WICHTIG: Diese Area MUSS mit OGB Raum-Namen übereinstimmen!
# OGB Konfiguration: opengrowbox.rooms[0].name = "dev_growbox"
# =====================================================
homeassistant:
  allowlist_external_dirs:
    - /config
  customize: {}

area:
  - name: "Dev GrowBox"
    id: dev_growbox

# =====================================================
# TEMPLATE SENSORS (als Basis für echte Sensors)
# =====================================================
template:
  - sensor:
      # LIGHT INTENSITY SENSOR
      - name: "Dev Light Intensity"
        unique_id: dev_light_intensity_01
        device_id: dev_light_main_01  # Zugehöriges Device
        area_id: dev_growbox
        unit_of_measurement: "%"
        value_template: "{{ states('input_number.dev_light_intensity') | float(0) }}"
        device_class: illuminance

      # TEMPERATURE SENSOR
      - name: "Dev Temperature"
        unique_id: dev_temperature_01
        device_id: dev_light_main_01  # Gleicheres Device (mehrere Sensors)
        area_id: dev_growbox
        unit_of_measurement: "°C"
        value_template: "{{ states('input_number.dev_temperature') | float(0) }}"
        device_class: temperature

      # HUMIDITY SENSOR
      - name: "Dev Humidity"
        unique_id: dev_humidity_01
        device_id: dev_light_main_01  # Gleicheres Device (mehrere Sensors)
        area_id: dev_growbox
        unit_of_measurement: "%"
        value_template: "{{ states('input_number.dev_humidity') | float(0) }}"
        device_class: humidity

      # CO2 SENSOR
      - name: "Dev CO2"
        unique_id: dev_co2_01
        device_id: dev_co2_device_01
        area_id: dev_growbox
        unit_of_measurement: "ppm"
        value_template: "{{ states('input_number.dev_co2') | float(0) }}"
        device_class: carbon_dioxide

      # MOISTURE SENSOR
      - name: "Dev Moisture"
        unique_id: dev_moisture_01
        device_id: dev_moisture_device_01
        area_id: dev_growbox
        unit_of_measurement: "%"
        value_template: "{{ states('input_number.dev_moisture') | float(0) }}"
        device_class: humidity

      # DEWPOINT SENSOR
      - name: "Dev Dewpoint"
        unique_id: dev_dewpoint_01
        device_id: dev_moisture_device_01  # Gleicheres Device (VWC + Dewpoint)
        area_id: dev_growbox
        unit_of_measurement: "°C"
        value_template: "{{ states('input_number.dev_dewpoint') | float(0) }}"
        device_class: temperature

# =====================================================
# INPUT NUMBERS (für Test-Werte)
# =====================================================
input_number:
  dev_light_intensity:
    name: "Dev Light Intensity"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    icon: mdi:lightbulb
    initial: 80

  dev_temperature:
    name: "Dev Temperature"
    min: 15
    max: 35
    step: 0.1
    unit_of_measurement: "°C"
    icon: mdi:thermometer
    initial: 24.5

  dev_humidity:
    name: "Dev Humidity"
    min: 30
    max: 80
    step: 1
    unit_of_measurement: "%"
    icon: mdi:water-percent
    initial: 60

  dev_co2:
    name: "Dev CO2"
    min: 400
    max: 2000
    step: 10
    unit_of_measurement: "ppm"
    icon: mdi:molecule-co2
    initial: 800

  dev_moisture:
    name: "Dev Moisture"
    min: 0
    max: 100
    step: 0.5
    unit_of_measurement: "%"
    icon: mdi:water
    initial: 55

  dev_dewpoint:
    name: "Dev Dewpoint"
    min: 10
    max: 25
    step: 0.1
    unit_of_measurement: "°C"
    icon: mdi:thermometer-low
    initial: 16.0

# =====================================================
# INPUT BOOLEANS (für Device-States)
# =====================================================
input_boolean:
  dev_light_on:
    name: "Dev Light On/Off"
    icon: mdi:lightbulb
    initial: true

  dev_heater_on:
    name: "Dev Heater On/Off"
    icon: mdi:heater
    initial: false

  dev_cooler_on:
    name: "Dev Cooler On/Off"
    icon: mdi:snowflake
    initial: false

  dev_humidifier_on:
    name: "Dev Humidifier On/Off"
    icon: mdi:water-plus
    initial: false

  dev_dehumidifier_on:
    name: "Dev Dehumidifier On/Off"
    icon: mdi:water-minus
    initial: false

  dev_exhaust_on:
    name: "Dev Exhaust On/Off"
    icon: mdi:fan
    initial: false

  dev_intake_on:
    name: "Dev Intake On/Off"
    icon: mdi:air-filter
    initial: false

  dev_co2_on:
    name: "Dev CO2 On/Off"
    icon: mdi:molecule-co2
    initial: false

# =====================================================
# TEMPLATE SWITCHES (als Device-Entitäten)
# =====================================================
switch:
  - platform: template
    name: "Dev Light Switch"
    unique_id: dev_light_switch_01
    device_id: dev_light_main_01
    area_id: dev_growbox
    value_template: "{{ states('input_boolean.dev_light_on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dev_light_on
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dev_light_on

  - platform: template
    name: "Dev Heater Switch"
    unique_id: dev_heater_switch_01
    device_id: dev_heater_device_01
    area_id: dev_growbox
    value_template: "{{ states('input_boolean.dev_heater_on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dev_heater_on
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dev_heater_on

  - platform: template
    name: "Dev Cooler Switch"
    unique_id: dev_cooler_switch_01
    device_id: dev_cooler_device_01
    area_id: dev_growbox
    value_template: "{{ states('input_boolean.dev_cooler_on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dev_cooler_on
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dev_cooler_on

  - platform: template
    name: "Dev Humidifier Switch"
    unique_id: dev_humidifier_switch_01
    device_id: dev_humidifier_device_01
    area_id: dev_growbox
    value_template: "{{ states('input_boolean.dev_humidifier_on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dev_humidifier_on
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dev_humidifier_on

  - platform: template
    name: "Dev Dehumidifier Switch"
    unique_id: dev_dehumidifier_switch_01
    device_id: dev_dehumidifier_device_01
    area_id: dev_growbox
    value_template: "{{ states('input_boolean.dev_dehumidifier_on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dev_dehumidifier_on
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dev_dehumidifier_on

  - platform: template
    name: "Dev Exhaust Switch"
    unique_id: dev_exhaust_switch_01
    device_id: dev_exhaust_device_01
    area_id: dev_growbox
    value_template: "{{ states('input_boolean.dev_exhaust_on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dev_exhaust_on
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dev_exhaust_on

  - platform: template
    name: "Dev Intake Switch"
    unique_id: dev_intake_switch_01
    device_id: dev_intake_device_01
    area_id: dev_growbox
    value_template: "{{ states('input_boolean.dev_intake_on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dev_intake_on
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dev_intake_on

  - platform: template
    name: "Dev CO2 Switch"
    unique_id: dev_co2_switch_01
    device_id: dev_co2_device_01
    area_id: dev_growbox
    value_template: "{{ states('input_boolean.dev_co2_on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dev_co2_on
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dev_co2_on

# =====================================================
# TEMPLATE LIGHTS (als Device-Entitäten)
# =====================================================
light:
  - platform: template
    name: "Dev Grow Light"
    unique_id: dev_light_main_01
    device_id: dev_light_main_01
    area_id: dev_growbox
    labels:
      - "light"  # WICHTIG: Definiert Device-Typ!
    value_template: "{{ states('input_boolean.dev_light_on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dev_light_on
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dev_light_on

  - platform: template
    name: "Dev Climate Control"
    unique_id: dev_climate_device_01
    device_id: dev_climate_device_01
    area_id: dev_growbox
    labels:
      - "climate"  # Definiert Climate Device
    value_template: "{{ states('input_boolean.dev_heater_on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dev_heater_on
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dev_heater_on
